### ISSUE TITLE
how can I download the archive inside debootstrap environment 

### ISSUE THREAD

**Issue by d2nikolic** [dgibson/dtc#120]
I see no clear link to use curl and download dtc-main archive. Only a link for .zip download, but debootstrap has no 'unzip' command in it. Any chance you can tell me how to pull tgz using curl?
Thank you,
Dragan

**Comment by dgibson** [comment]
I have no idea what archive you're looking at that has .zip downloads.  The primary download archive for dtc is at [https://mirrors.edge.kernel.org/pub/software/utils/dtc/](https://mirrors.edge.kernel.org/pub/software/utils/dtc/) which is all .tar.gz.

**Comment by d2nikolic** [comment]
What used to work in bullseye Debian 11.7 is the following:

curl -kL https://github.com/RedPitaya/dtc/archive/overlays.tar.gz -o dtc.tar.gz
tar zxvf dtc.tar.gz
cd dtc-overlays
# Fix duplicate declaration of yylloc
sed -i -e '/YYLTYPE yylloc/d' dtc-lexer.l
make
make install PREFIX=/usr

but now in Debian bookworm this fails

**Comment by dgibson** [comment]
That's a third party fork of dtc by someone else ("Red Pitaya", whoever they are), itself based on another fork of dtc.  It's not my archive, and it's a modified version of my code, so I really can't answer anything about it.  You'll need to contact Red Pitaya.
