### ISSUE TITLE
libfdt/fdt_overlay.c has ambiguous license

### ISSUE THREAD

**Issue by ardbiesheuvel** [dgibson/dtc#14]
libfdt/fdt_overlay.c has no license header, and libfdt/ has no LICENSE file of its own, which makes it unclear whether fdt_overlay.c may be distributed under the same terms as the remainder of libfdt, or under the GPL which covers dtc and other parts of the code.

**Comment by dgibson** [comment]
So, it was certainly my intention and expectation that all of libfdt be GPL/BSD dual licensed.  But I guess I'd better go double check that the author of fdt_overlay.c had the same expectation.

**Comment by dgibson** [comment]
I've chased up the contributors and gotten a copyright banner added by the main author.

As expected it is licensed as the rest of libfdt.
