### ISSUE TITLE
fdt_next_node() return value depends on VALID_INPUT

### ISSUE THREAD

**Issue by frankmehnert** [dgibson/dtc#39]
The `fdt_next_node()` function calls `fdt_check_node_offset_()` to verify if the resulting offset is valid. The function `fdt_check_node_offset_()` returns without any further check if the `VALID_INPUT` flag is set at `FDT_ASSUME_MASK`.

If the `VALID_INPUT` flag is not set then fdt_check_node_offset_() calls
```
fdt_next_tag(fdt, offset, &offset)
```
and passes the returned offset to the caller. This offset can be different from the original offset.

I'm trying to iterate over a tree using
```
fdt_for_each_subnode(node, fdt, parent)
```
This works only if I disable `VALID_INPUT`.

**Comment by dgibson** [comment]
Can you confirm if the latest push fixes this?  If so we can close this issue.

**Comment by frankmehnert** [comment]
Confirmed. Thanks!
