### ISSUE TITLE
fdt_strerror missing FDT alignment error in 1.6.1

### ISSUE THREAD

**Issue by kallisti5** [dgibson/dtc#56]
Getting "unknown error"...
```
fdt_register_node ERROR: fdt_get_name -19 - <unknown error>
```

FDT_ERR_ALIGNMENT seems to be missing in fdt_strerror in 1.6.1.

Any chance of a 1.6.2 version?   :-)

**Comment by dgibson** [comment]
> Any chance of a 1.6.2 version? :-)

Uh.. sure?  I just need to find time to do it.

**Comment by dgibson** [comment]
Closing, since remaining issue is a duplicate of #75
