### ISSUE TITLE
Python test suite fails

### ISSUE THREAD

**Issue by rossburton** [dgibson/dtc#60]
With current master the Python test suite fails:

```
FAIL: testHeader (__main__.PyLibfdtBasicTests)
Test that we can access the header values
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./pylibfdt_tests.py", line 295, in testHeader
    self.assertEqual(self.fdt.size_dt_strings(), 105)
AssertionError: 97 != 105
```

**Comment by dgibson** [comment]
Is this related to the PY_SSIZE_T thing?  This is a different error, but now that I've applied that fix, the testsuite is passing for me.

**Comment by rossburton** [comment]
No, it's fixed by "pylibfdt_tests: Don't depend on built dtbs" patch from Rob.  Depending on how you run the tests changes the DTBs that are used.
