### ISSUE TITLE
pkg-config check for python always fails

### ISSUE THREAD

**Issue by lordelectrode** [dgibson/dtc#8]
https://github.com/dgibson/dtc/blob/master/Makefile#L132
Only python2 and python3 exist on archlinux (which i presume is as close to upstream as possible)

**Comment by dgibson** [comment]
I really have no idea what you're trying to say here.

**Comment by lordelectrode** [comment]
`$(PKG_CONFIG) --cflags python` will always fail regardless of either/both python versions being installed

**Comment by lordelectrode** [comment]
`if (layer > 0x01)` seems to work

**Comment by dgibson** [comment]
So, changing it to $(PKG_CONFIG) --cflags python2 might work, since I believe the Python code is built for Python2, not Python3.  I'd have to check if that still works on more common distros than archlinux, though.

**Comment by lordelectrode** [comment]
https://www.python.org/dev/peps/pep-0394/

**Comment by dgibson** [comment]
I just pushed a commit to fix this to master.

Sorry it's taken so long, I've been a bit swamped.  Mind you, making your report in clear sentences rather than cryptic URL references wouldn't have hurt.
